queue: 'Hosted Linux Preview'

variables:
  - Major: '1'
  - Minor: '0'
  - Patch: '0'

steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*[Tt]ests/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - task: NuGetCommand@2
    inputs:
      command: pack
      packagesToPack: '**/*.csproj'
      configuration: '$(BuildConfiguration)'
      versioningScheme: byPrereleaseNumber
      majorVersion: '$(Major)'
      minorVersion: '$(Minor)'
      patchVersion: '$(Patch)'

  - task: NuGetCommand@2
    inputs:
      command: push
      publishFeedCredentials: 'OSS'
      nuGetFeedType: external
      versioningScheme: byPrereleaseNumber
      majorVersion: '$(Major)'
      minorVersion: '$(Minor)'
      patchVersion: '$(Patch)'
      
  - task: PublishBuildArtifacts@1
